config/routes.rb
Rails.application.routes.draw do
  resources :itaewon_records
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itaewon_record.rb
class ItaewonRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/itaewon_records_controller.rb
class ItaewonRecordsController < ApplicationController
  before_action :set_itaewon_record, only: %i[ show edit update destroy ]

  # GET /itaewon_records or /itaewon_records.json
  def index
    @itaewon_records = ItaewonRecord.all
  end

  # GET /itaewon_records/1 or /itaewon_records/1.json
  def show
  end

  # GET /itaewon_records/new
  def new
    @itaewon_record = ItaewonRecord.new
  end

  # GET /itaewon_records/1/edit
  def edit
  end

  # POST /itaewon_records or /itaewon_records.json
  def create
    @itaewon_record = ItaewonRecord.new(itaewon_record_params)

    respond_to do |format|
      if @itaewon_record.save
        format.html { redirect_to itaewon_record_url(@itaewon_record), notice: "Itaewon record was successfully created." }
        format.json { render :show, status: :created, location: @itaewon_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @itaewon_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itaewon_records/1 or /itaewon_records/1.json
  def update
    respond_to do |format|
      if @itaewon_record.update(itaewon_record_params)
        format.html { redirect_to itaewon_record_url(@itaewon_record), notice: "Itaewon record was successfully updated." }
        format.json { render :show, status: :ok, location: @itaewon_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @itaewon_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itaewon_records/1 or /itaewon_records/1.json
  def destroy
    @itaewon_record.destroy

    respond_to do |format|
      format.html { redirect_to itaewon_records_url, notice: "Itaewon record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itaewon_record
      @itaewon_record = ItaewonRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def itaewon_record_params
      params.require(:itaewon_record).permit(:lat, :lng, :name, :url, :when)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itaewon_records_helper.rb
module ItaewonRecordsHelper
end

app/views/itaewon_records/_form.html.erb
<%= form_with(model: itaewon_record, local: true) do |form| %>
  <% if itaewon_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(itaewon_record.errors.count, "error") %> prohibited this itaewon_record from being saved:</h2>

      <ul>
        <% itaewon_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :when %>
    <%= form.datetime_select :when %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/itaewon_records/edit.html.erb
<h1>Editing Itaewon Record</h1>

<%= render 'form', itaewon_record: @itaewon_record %>

<%= link_to 'Show', @itaewon_record %> |
<%= link_to 'Back', itaewon_records_path %>

app/views/itaewon_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itaewon Records</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Name</th>
      <th>Url</th>
      <th>When</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itaewon_records.each do |itaewon_record| %>
      <tr>
        <td><%= itaewon_record.lat %></td>
        <td><%= itaewon_record.lng %></td>
        <td><%= itaewon_record.name %></td>
        <td><%= itaewon_record.url %></td>
        <td><%= itaewon_record.when %></td>
        <td><%= link_to 'Show', itaewon_record %></td>
        <td><%= link_to 'Edit', edit_itaewon_record_path(itaewon_record) %></td>
        <td><%= link_to 'Destroy', itaewon_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itaewon Record', new_itaewon_record_path %>

app/views/itaewon_records/new.html.erb
<h1>New Itaewon Record</h1>

<%= render 'form', itaewon_record: @itaewon_record %>

<%= link_to 'Back', itaewon_records_path %>

app/views/itaewon_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @itaewon_record.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @itaewon_record.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @itaewon_record.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @itaewon_record.url %>
</p>

<p>
  <strong>When:</strong>
  <%= @itaewon_record.when %>
</p>

<%= link_to 'Edit', edit_itaewon_record_path(@itaewon_record) %> |
<%= link_to 'Back', itaewon_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itaewon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>